name := "ModelConstructor"
version := "0.1.4"
scalaVersion := "2.12.3"
organization := "ru.ispras.dst"

libraryDependencies += "org.jgrapht" % "jgrapht-core" % "1.0.1"
libraryDependencies += "org.jgrapht" % "jgrapht-ext" % "1.0.1"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.0"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.0" % "test"
libraryDependencies += "org.scala-lang.modules" % "scala-xml_2.12" % "1.0.6"
